

 export const menuItems = [
  {
    id: 1,
    name: "Nom banh chok",
    descriptions: "Num banhchok are lightly fermented Cambodian rice noodles and a breakfast noodle dish. banhchok បញ្ចុក translates to to feed in Khmer language. ",
    price: 5.5,
    quantity: 0,
    image: "https://grantourismotravels.com/wp-content/uploads/2021/02/Authentic-Nom-Banh-Chok-Recipe-Cambodian-Khmer-Noodles-Copyright-2021-Terence-Carter-Grantourismo.jpg",
  },
  {
    id: 2,
    name: "Fish amok",
    descriptions: "Fish amok or amok trei is a Khmer steamed fish curry with a mousse-like consistency, considered one of Cambodia's national dishes. Fish amok is believed to have been a royal Khmer dish dating back to the Khmer Empire, although some question it originating in Cambodia.",
    price: 5.7,
    quantity: 0,
    image: "https://www.traveltalktours.com/wp-content/smush-webp/2021/10/taste-fish-amok-in-cambodia.jpeg.webp",
  },
  {
    id: 3,
    name: "ទឺកគ្រឿង",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 3.0,
    quantity: 0,
    image: "https://www.luxurycruisemekong.com/wp-content/uploads/2016/11/Traditional-Khmer-food.jpg",
  },
  {
    id: 4,
    name: "Prahok Ktiss",
    descriptions: "Prahok ktis is a Cambodian dipping sauce made from prahok sach, minced pork, yellow kroeung, coconut cream, tamarind water, palm sugar, pea eggplants and kaffir lime leaves. Pea eggplants can also be replaced with green apples, unripe peaches or nectarines, cabbage or cauliflower",
    price: 2.5,
    quantity: 0,
    image: "https://angkorchef.com/wp-content/uploads/2020/04/IMG_8444-web.jpeg",
  },
  {
    id: 5,
    name: "ទឹកប្រហុកពោះជ្រូក",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 5.5,
    quantity: 0,
    image: "https://www.traveltalktours.com/wp-content/smush-webp/2021/10/taste-beef-lok-lak-in-cambodia.jpeg.webp",
  },
  {
    id: 6,
    name: "Red Tree Ants with Beef",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 6.5,
    quantity: 0,
    image: "https://cdn.pixabay.com/photo/2018/10/25/06/00/khmer-food-3771719_1280.jpg",
  },
  {
    id: 7,
    name: "Beef Lok Lak",
    descriptions: "Beef lok lak is a classic Khmer dish made using stir fried strips of tender beef served on a bed of lettuce, sliced tomatoes, cucumbers and rings of raw onions. ",
    price: 2.7,
    quantity: 0,
    image: "https://www.cambodiaembassyuk.org/wp-content/uploads/2021/12/7-Beef-Lok-Lak-1024x640.webp",
  },
  {
    id: 8,
    name: "Lap Khmer",
    descriptions: "Lap Khmer is also known as Khmer beef salad, in which thinly sliced beef can be quickly seared or mostly marinated in lime juice. This ceviche-styled dish bursts with flavors of lemongrass, shallots, garlic, fish sauce, Asian basil, mint, green beans, and bell peppers. ",
    price: 5.7,
    quantity: 0,
    image: "https://www.cambodiaembassyuk.org/wp-content/uploads/2021/12/8-Lap-Khmer-1024x546.webp",
  },
  {
    id: 9,
    name: "Cambodian BBQ",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 4.6,
    quantity: 0,
    image: "https://www.traveltalktours.com/wp-content/smush-webp/2021/10/taste-cambodian-bbq.jpeg.webp",
  },
];
