

 export const menuItems = [
  {
    id: 1,
    name: "សម្លរ កកូរ",
    descriptions: "សម្លកកូរ គឺជាសម្លបែបប្រពៃណីរបស់កម្ពុជា។ សម្លនេះ​ត្រូវ​បាន​គេ​ចាត់​ទុក​ជា​មុខ​ម្ហូប​មួយចំណោមសម្លផ្សេងៗទៀត​របស់​ជាតិខ្មែរ​ផង​ដែរ។",
    price: 5.5,
    quantity: 0,
    image: "https://www.luxurycruisemekong.com/wp-content/uploads/2016/11/Traditional-Khmer-food.jpg",
  },
  {
    id: 2,
    name: "សម្លរម្ជូរ",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 5.7,
    quantity: 0,
    image: "https://www.luxurycruisemekong.com/wp-content/uploads/2016/11/Traditional-Khmer-food.jpg",
  },
  {
    id: 3,
    name: "ទឺកគ្រឿង",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 3.0,
    quantity: 0,
    image: "https://www.luxurycruisemekong.com/wp-content/uploads/2016/11/Traditional-Khmer-food.jpg",
  },
  {
    id: 4,
    name: "មាន់​​ដុត",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 2.5,
    quantity: 0,
    image: "https://www.luxurycruisemekong.com/wp-content/uploads/2016/11/Traditional-Khmer-food.jpg",
  },
  {
    id: 5,
    name: "ទឹកប្រហុកពោះជ្រូក",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 5.5,
    quantity: 0,
    image: "https://wander-lush.org/wp-content/uploads/2019/04/53604549_249808029255312_6796905223130219574_n.jpg",
  },
  {
    id: 6,
    name: "ញៀនកំពឹស",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 6.5,
    quantity: 0,
    image: "https://cdn.pixabay.com/photo/2018/10/25/06/00/khmer-food-3771719_1280.jpg",
  },
  {
    id: 7,
    name: "ទឹកគ្រឿង",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 2.7,
    quantity: 0,
    image: "https://wander-lush.org/wp-content/uploads/2019/09/Emily-Lush-Khmer-food-Phnom-Penh-4-2.jpg",
  },
  {
    id: 8,
    name: "សម្លរម្រះ",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 5.7,
    quantity: 0,
    image: "https://i.pinimg.com/736x/47/41/44/47414448166bc99e09878559ade8ed6d.jpg",
  },
  {
    id: 9,
    name: "ត្រីអាំង",
    descriptions: "ksd;fkajsd;fklasjd;fasd;fasdf;askdfjakdsfa",
    price: 4.6,
    quantity: 0,
    image: "https://cambodiatravel.com/images/2020/10/Beef-Lok-Lak-cambodia.jpg",
  },
];
